name: Sunset's Claim CI

on:
  push:
    branches:
      - dev, release
  pull_request:
    branches:
      - dev, release

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display folder structure
        run: tree -L 2